In [1]:
import numpy as np

In [21]:
pool = (np.random.rand(2,3)*10).astype(np.int16)
print(pool)

idx = [0,1,1,0]

angle = pool[idx]

print(angle)

[[1 0 0]
 [3 7 7]]
[[1 0 0]
 [3 7 7]
 [3 7 7]
 [1 0 0]]
