In [32]:
import numpy as np

T = 125
F = 257

L_t = 2
L_f = 0

mat = np.zeros((F+T))

for t in range(2*L_t+1) : 
    for f in range(2*L_f+1):
        f_s = f
        f_e = F+f
        
        t_s = t
        t_e = T+t
        
        print("{}:{}:{} | {}:{}:{}".format(f_s,f_e,len(mat[f_s:f_e]),t_s,t_e,len(mat[t_s:t_e])))

0:257:257 | 0:125:125
0:257:257 | 1:126:125
0:257:257 | 2:127:125
0:257:257 | 3:128:125
0:257:257 | 4:129:125


In [1]:
import torch

/home/kbh/.conda/envs/dnn/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [18]:
x = (torch.rand(3,1,2)*10).to(torch.int32)
y = (torch.rand(3,2,1)*10).to(torch.int32)

In [19]:
print(x.shape)
print(y.shape)

z = torch.bmm(x,y)
print(z.shape)

print(x)
print(y)
print(z)

torch.Size([3, 1, 2])
torch.Size([3, 2, 1])
torch.Size([3, 1, 1])
tensor([[[0, 4]],

        [[3, 7]],

        [[8, 3]]], dtype=torch.int32)
tensor([[[6],
         [1]],

        [[2],
         [1]],

        [[2],
         [2]]], dtype=torch.int32)
tensor([[[ 4]],

        [[13]],

        [[22]]], dtype=torch.int32)
