In [216]:
import torch
import torch.nn as nn

# force re-import
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [217]:
from Attractor import DirectionAttractorNet

B = 2
C = 4
mic_pos = [[0,0,0],[1,0,0],[0,1,0],[1,1,0]]

m = DirectionAttractorNet().to("cuda:0")

x  = torch.rand(B,C,16000).to("cuda:0")
angle = (torch.rand(B)*360).to("cuda:0")
y = m(x,angle,torch.tensor(mic_pos).unsqueeze(0).to("cuda:0"))
print(y.shape)

torch.Size([2, 16000])


In [63]:
x = torch.arange(0,3)
print(x.shape)

torch.Size([3])


# Shape

In [199]:
B = 2
C = 3
F = 4
T = 5

X = torch.rand(B,C,F,T,dtype=torch.cfloat)*2-1
M = torch.rand(B,F,T)
v = torch.rand(B,1,T)

print("== input == ")
print("X : {}".format(X.shape))
print("M : {}".format(M.shape))
print("v : {}".format(v.shape))

#print(M)
#print(v)

# X * X^H

X__ = torch.permute(X,(0,2,3,1))
X__ = torch.reshape(X__,(B*F*T,C,1))
M__ = torch.reshape(M,(B*F*T,1,1))
v__ = v.expand(B,F,T)
v__ = torch.reshape(v__,(B*F*T,1,1))
print("== batchwise == ")
print("X : {}".format(X__.shape))
print("M : {}".format(M__.shape))
print("v : {}".format(v__.shape))

#print(M__)
#print(v__)

R = torch.bmm(X__,torch.permute(X__,(0,2,1)))
print("R : {}".format(R.shape))
# masking
R *= v__
R *= M__

R = R + torch.eye(C)*1e-4

R_inv =  torch.inverse(R)

#R = torch.reshape(R,(B,F,T,C,C))

print(R.shape)
print(R_inv.shape)

W = torch.bmm(R,R_inv)
print(W.shape)

== input == 
X : torch.Size([2, 3, 4, 5])
M : torch.Size([2, 4, 5])
v : torch.Size([2, 1, 5])
== batchwise == 
X : torch.Size([40, 3, 1])
M : torch.Size([40, 1, 1])
v : torch.Size([40, 1, 1])
R : torch.Size([40, 3, 3])
torch.Size([40, 3, 3])
torch.Size([40, 3, 3])
torch.Size([40, 3, 3])


In [153]:
x = torch.rand(3,4,4)
x_inv = torch.inverse(x)
torch.bmm(x,x_inv)

tensor([[[ 1.0000e+00,  5.5879e-09, -5.9605e-08,  0.0000e+00],
         [ 0.0000e+00,  1.0000e+00,  5.9605e-08, -5.9605e-08],
         [ 5.9605e-08,  3.5390e-08,  1.0000e+00,  0.0000e+00],
         [-1.5646e-07, -5.0757e-08, -7.4506e-08,  1.0000e+00]],

        [[ 1.0000e+00,  1.7881e-07,  0.0000e+00,  7.1526e-07],
         [-1.4901e-07,  1.0000e+00,  4.7684e-07,  7.1526e-07],
         [-2.9802e-08,  5.9605e-08,  1.0000e+00,  1.1921e-07],
         [ 2.9802e-08, -1.4901e-08,  1.1921e-07,  1.0000e+00]],

        [[ 1.0000e+00,  7.1526e-07,  4.7684e-07, -9.5367e-07],
         [-1.9073e-06,  1.0000e+00,  0.0000e+00, -4.7684e-07],
         [-2.8610e-06,  0.0000e+00,  1.0000e+00,  4.7684e-07],
         [-2.3842e-06,  7.1526e-07,  0.0000e+00,  1.0000e+00]]])

In [173]:
C = torch.rand(3,1,dtype=torch.cfloat)
print(C)

torch.matmul(C,C.H)

tensor([[0.3625+0.4254j],
        [0.4639+0.6417j],
        [0.7367+0.2248j]])


tensor([[0.3124-9.7332e-10j, 0.4411-3.5302e-02j, 0.3627+2.3188e-01j],
        [0.4411+3.5302e-02j, 0.6270-1.1783e-08j, 0.4860+3.6847e-01j],
        [0.3627-2.3188e-01j, 0.4860-3.6847e-01j, 0.5932-6.2595e-09j]])